    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pranav
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
public class MainGUI extends javax.swing.JFrame {
    /**
     * Creates new form MainGUI
     */
    DefaultTableModel d=null;
    JDBC jd=null;
    String dat="SELECT CURDATE()";
    String dat1=null;
    String w;
    String z1,z2,z3,z4,z5,z6;
    public MainGUI() {
        initComponents();
        jd=new JDBC();
        jd.make();
        d=(DefaultTableModel)jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("List Of Books Available");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButton1.setText("Display list of all available books");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jRadioButton1.setText("Book");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jRadioButton2.setText("Author");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setText("Search....");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jButton3.setText("Take Selected Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Enter The ID Of The Book You Want To Take");

        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Return Borrowed Books By Entering The ID");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jButton4.setText("Return Selected Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Author", "Language", "Publisher", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButton5.setText("Display all books currently taken by user ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel3.setText("Logged In As ");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel2.setText("Main Library Interface");

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButton6.setText("Log Out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButton7.setText("Reset Fields");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(77, 77, 77)
                                .addComponent(jButton5)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(48, 48, 48)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton2))
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)
                                        .addGap(81, 81, 81))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(31, 31, 31))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1)
                        .addGap(79, 79, 79)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton1))
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql;
        String sql1=jTextField1.getText();
        if (jRadioButton1.isSelected()) {
            int rc=d.getRowCount();
            if (rc>0) {
                d.setRowCount(0);
            }
            dat="SELECT CURDATE()";
            sql="SELECT * FROM BOOKS WHERE BOOK_NAME LIKE '%"+sql1+"%' AND STAT='"+"AVAILABLE"+"'";
            try {
                jd.rs=jd.st.executeQuery(sql);
                ResultSet rs1=jd.rs;
                String a2,b2,c2,d2,e2; 
                while(rs1.next()) {
                    a2=rs1.getString("B_ID");
                    b2=rs1.getString("BOOK_NAME");
                    c2=rs1.getString("AUTHOR");
                    d2=rs1.getString("BOOK_LANG");
                    e2=rs1.getString("PUBLISHER");
                    d.addRow(new String[]{a2,b2,c2,d2,e2});
                }
                
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            
            
        }
        else if (jRadioButton2.isSelected()) {
            int rc=d.getRowCount();
            if (rc>0) {
                d.setRowCount(0);
            }
            sql="SELECT * FROM BOOKS WHERE AUTHOR LIKE '%"+sql1+"%' AND STAT='"+"AVAILABLE"+"'";
            try {
                jd.rs=jd.st.executeQuery(sql);
                ResultSet rs1=jd.rs;
                String a2,b2,c2,d2,e2;
                while(rs1.next()) {
                    a2=rs1.getString("B_ID");
                    b2=rs1.getString("BOOK_NAME");
                    c2=rs1.getString("AUTHOR");
                    d2=rs1.getString("BOOK_LANG");
                    e2=rs1.getString("PUBLISHER");
                    d.addRow(new String[]{a2,b2,c2,d2,e2});
                }
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rc=d.getRowCount();
        if (rc>0) {
            d.setRowCount(0);
        }
            String sql="SELECT * FROM BOOKS WHERE STAT='"+"AVAILABLE"+"'";
            try {
                ResultSet e=jd.st.executeQuery(sql);
                String a1,a2,a3,a4,a5;
                while (e.next()) {
                    a1=e.getString("B_ID");
                    a2=e.getString("book_name");
                    a3=e.getString("Author");
                    a4=e.getString("BOOK_LANG");
                    a5=e.getString("PUBLISHER");
                    d.addRow(new String[]{a1,a2,a3,a4,a5});
                
                }    
            
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(null);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql=null;
        int rc=d.getRowCount();
        if (rc>0) {
            d.setRowCount(0);
        }
        third: {
            String sql1="SELECT * FROM USERS WHERE USR_ID='"+w+"'";
            try {
                ResultSet rs8=jd.st.executeQuery(dat);
                if(rs8.next()) {
                    dat1=rs8.getString("CURDATE()");
                }
                ResultSet rs1=jd.st.executeQuery(sql1);
                if (rs1.next()) {
                    String a=rs1.getString("B_ID1");
                    String b=rs1.getString("B_ID2");
                    String c=rs1.getString("B_ID3");
                    String d1=rs1.getString("B_ID4");
                    String e=rs1.getString("B_ID5");
                    if (a==null && b==null && c==null && d1==null && e==null) {
                        JOptionPane.showMessageDialog(null," You Have Not Borrowed Any Books ");
                        break third;
                    }
                    else {
                        sql="SELECT * FROM BOOKS WHERE B_ID='"+a+"' OR B_ID='"+b+"' OR B_ID='"+c+"' OR B_ID='"+d1+"' OR B_ID='"+e+"'";
                    }
                    jd.rs=jd.st.executeQuery(sql);
                    ResultSet b9=jd.rs;
                    String a1,a2,a3,a4,a5,a6,dom,statuses;
                    while(b9.next()) {
                        a1=b9.getString("B_ID");
                        a2=b9.getString("book_name");
                        a3=b9.getString("Author");
                        a4=b9.getString("BOOK_LANG");
                        a5=b9.getString("PUBLISHER");
                        a6=b9.getString("DAT");
                        String date1=dat1.substring(0,4)+dat1.substring(5,7)+dat1.substring(8,10);
                        String date2=a6.substring(0,4)+a6.substring(5,7)+a6.substring(8,10);
                        int dee1=Integer.parseInt(date1);
                        int dee2=Integer.parseInt(date2);
                        int change=dee1-dee2;
                        if(change>3) {
                            statuses="Due";
                        }
                        else {
                            statuses="Not Due";
                        }
                        d.addRow(new String[]{a1,a2,a3,a4,a5,statuses});
                    }    
                }
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s=jTextField2.getText();
        s.trim();
        if(s.equals("")) {
            JOptionPane.showMessageDialog(null," Please Enter A Book ID ");
        }
        else {
            first:{
                String sql1="SELECT * FROM USERS WHERE USR_ID='"+w+"'";
                String sql5="SELECT * FROM BOOKS WHERE B_ID='"+s+"' AND STAT='Available'";
                String sql=null;
                String sql2=null;
                try {
                    ResultSet am=jd.st3.executeQuery(dat);
                    ResultSet re=jd.st.executeQuery(sql1);
                    if(am.next()) {
                        dat1=am.getString("CURDATE()");
                    }
                    if (re.next()) {
                         ResultSet re2=jd.st2.executeQuery(sql5);
                         if (re2.next()) {
                            z1=re.getString("B_ID1");
                            z2=re.getString("B_ID2");
                            z3=re.getString("B_ID3");
                            z4=re.getString("B_ID4");
                            z5=re.getString("B_ID5");
                            if(z1==null) {
                                sql="UPDATE USERS SET B_ID1='"+s+"' WHERE USR_ID='"+w+"'";
                                sql2="UPDATE BOOKS SET STAT='TAKEN',TAKEN_BY='"+w+"',DAT='"+dat1+"' WHERE B_ID='"+s+"'";     
                            }
                            else if (z1!=null && z2==null) {
                                sql="UPDATE USERS SET B_ID2='"+s+"' WHERE USR_ID='"+w+"'";
                                sql2="UPDATE BOOKS SET STAT='TAKEN',TAKEN_BY='"+w+"',DAT='"+dat1+"' WHERE B_ID='"+s+"'";
                            }
                            else if (z1!=null && z2!=null && z3==null) {
                                sql="UPDATE USERS SET B_ID3='"+s+"' WHERE USR_ID='"+w+"'";
                                sql2="UPDATE BOOKS SET STAT='TAKEN',TAKEN_BY='"+w+"',DAT='"+dat1+"' WHERE B_ID='"+s+"'";
                            }
                            else if (z1!=null && z2!=null && z3!=null && z4==null && z6.equals("LEGEND")) {
                                sql="UPDATE USERS SET B_ID4='"+s+"' WHERE USR_ID='"+w+"'";
                                sql2="UPDATE BOOKS SET STAT='TAKEN',TAKEN_BY='"+w+"',DAT='"+dat1+"' WHERE B_ID='"+s+"'";
                            }
                            else if (z1!=null && z2!=null && z3!=null && z4!=null && z5==null && z6.equals("LEGEND")) {
                                sql="UPDATE USERS SET B_ID5='"+s+"' WHERE USR_ID='"+w+"'";
                                sql2="UPDATE BOOKS SET STAT='TAKEN',TAKEN_BY='"+w+"',DAT='"+dat1+"' WHERE B_ID='"+s+"'";
                            }
                            else if (z1!=null && z2!=null && z3!=null && z4==null && z6.equals("NORMAL")) {
                                JOptionPane.showMessageDialog(null," To take more than 3 books you will have to become a legend member ");
                                break first;
                            }
                            int val=jd.st.executeUpdate(sql);
                            int val2=jd.st.executeUpdate(sql2);
                            if (val>0 && val2>0) {
                                JOptionPane.showMessageDialog(null," Book Successfully Taken ");
                            }
                            else if (val<0 || val2<0) {
                                JOptionPane.showMessageDialog(null," Issue Of Book Failed Please Contact The Administrator ");
                            }
                    }
                    else {
                            JOptionPane.showMessageDialog(null," Book ID Does Not Exist. Please Check Your Entry ");
                    }
                    }
                }
                    catch(Exception e) {
                        JOptionPane.showMessageDialog(null,e.getMessage());
                    }
                }    
            }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String b1,b2,b3,b4,b5;
        String sql0=null;
        String sql01=null;
        String s=jTextField3.getText();
        s.trim();
        if (s.equals("")) {
            JOptionPane.showMessageDialog(null," Please Enter A Book ID ");
        }
        else {
            second: {
                String sql="SELECT * FROM USERS WHERE USR_ID='"+w+"' AND (B_ID1='"+s+"' OR B_ID2='"+s+"' OR B_ID3='"+s+"' OR B_ID4='"+s+"' OR B_ID5='"+s+"')";
                try {
                    ResultSet rse=jd.st.executeQuery(sql);
                    if (rse.next()) {
                        b1=rse.getString("B_ID1");
                        b2=rse.getString("B_ID2");
                        b3=rse.getString("B_ID3");
                        b4=rse.getString("B_ID4");
                        b5=rse.getString("B_ID5");
                        if (s.equals(b1)) {
                            sql0="UPDATE USERS SET B_ID1=null WHERE USR_ID='"+w+"'";
                            sql01="UPDATE BOOKS SET STAT='Available',TAKEN_BY=null,DAT=null WHERE B_ID='"+b1+"'";
                        }
                        else if (s.equals(b2)) {
                            sql0="UPDATE USERS SET B_ID2=null WHERE USR_ID='"+w+"'";
                            sql01="UPDATE BOOKS SET STAT='Available',TAKEN_BY=null,DAT=null WHERE B_ID='"+b2+"'";
                        }
                        else if (s.equals(b3)) {
                            sql0="UPDATE USERS SET B_ID3=null WHERE USR_ID='"+w+"'";
                            sql01="UPDATE BOOKS SET STAT='Available',TAKEN_BY=null,DAT=null WHERE B_ID='"+b3+"'";
                        }
                        else if (s.equals(b4)) {
                            sql0="UPDATE USERS SET B_ID4=null WHERE USR_ID='"+w+"'";
                            sql01="UPDATE BOOKS SET STAT='Available',TAKEN_BY=null,DAT=null WHERE B_ID='"+b4+"'";
                        }
                        else if (s.equals(b5)) {
                            sql0="UPDATE USERS SET B_ID5=null WHERE USR_ID='"+w+"'";
                            sql01="UPDATE BOOKS SET STAT='Available',TAKEN_BY=null,DAT=null WHERE B_ID='"+b5+"'";
                        }
                        int ret=jd.st.executeUpdate(sql0);
                        int ret2=jd.st.executeUpdate(sql01);
                        if (ret>0 && ret2>0) {
                            JOptionPane.showMessageDialog(null," Book Successfully Returned ");
                        }
                        else if (ret<0 || ret2<0) {
                            JOptionPane.showMessageDialog(null," Book Not Returned Properly Please Contact The Administrator ");
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(null," Please Enter A Valid Book ID ");
                    }
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            jd.con.close();
            jd.st.close();
        }
        catch(Exception f) {
            JOptionPane.showMessageDialog(null,f.getMessage());
        }
        JOptionPane.showMessageDialog(null," Sayonara ");
        LoginGUI l=new LoginGUI();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("Search...");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
