CREATE TABLE BOOKS (
	B_ID VARCHAR(30) PRIMARY KEY,
    BOOK_NAME VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(20) NOT NULL,
    STAT VARCHAR(10) NOT NULL,
    PUBLISHER VARCHAR(20) NOT NULL,
    BOOK_LANG VARCHAR(10) NOT NULL
);